### ISSUE TITLE
Strip Authentication string from headers

### ISSUE THREAD

**Issue by br4in3x** [dnaeon/go-vcr#35]
Hello! 

I was wondering, is there any way of modifying what is being dumped to the recorded response? For example, in the original ruby `vcr` gem there is an option to [`filter_sensitive_data`](https://relishapp.com/vcr/vcr/v/3-0-1/docs/configuration/filter-sensitive-data), but for `go-vcr` package I can't figure out a way how to do the same.

Currently, I'm doing this as a quick workaround, but I don't think that it's the best way to do that:

```go
if copiedReq.Header["Authorization"] != nil {
  copiedReq.Header["Authorization"] = []string{"<FILTERED>"}
}

// Add interaction to cassette
interaction := &cassette.Interaction{
  Request: cassette.Request{
    Headers: copiedReq.Header,
    ...
  },
  ...
}
```

Could anyone suggest how to do that better? Maybe we can introduce configurable `Interaction` struct which will be an optional parameter of a `New`?

**Comment by br4in3x** [comment]
Solved by finding solution across forks! Thanks to  @judy2k and his commit: https://github.com/judy2k/go-vcr/commit/0f4bcdc832aeefa2fdeec76071fcdddb1e1c2eb6

For those who will wonder how to do the same, this is example usage of his change:

```go
r, err := recorder.New("fixtures/" + fixtureName)
r.SetFilter(func(i *cassette.Interaction) error {
  if i.Request.Headers["Authorization"] != nil {
    i.Request.Headers["Authorization"] = []string{"<FILTERED>"}
  }
  return nil
})
```

**Comment by judy2k** [comment]
Cool! I should have opened a PR 😬

**Comment by dnaeon** [comment]
@judy2k It's still not late to do that :) I'll re-open the issue in case you'd like to make the PR.

A small improvement suggestion would be to allow setting multiple filter functions :)

Thanks,
Marin

**Comment by judy2k** [comment]
Okay, I've just opened PR #36 which allows the adding of one (or more!) filter functions.

**Comment by dnaeon** [comment]
Thanks a lot, @judy2k !
